[project]
name = "aiclinic-pge2-1-sem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kagglehub>=0.3.13",
    "mistralai>=1.9.11",
    "pdfplumber>=0.11.8",
    "pypdf2>=3.0.1",
    "scikit-learn>=1.7.2",
]
